// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package pb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,6,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,8,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,9,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,10,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,11,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,12,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,13,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,16,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	UserID               string   `protobuf:"bytes,17,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *LoginResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *LoginResponse) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *LoginResponse) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *LoginResponse) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *LoginResponse) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *LoginResponse) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *LoginResponse) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *LoginResponse) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *LoginResponse) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *LoginResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LoginResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *LoginResponse) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

func (m *LoginResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RegisterRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,5,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,7,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,8,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,9,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,10,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,11,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,12,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,15,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegisterRequest) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *RegisterRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *RegisterRequest) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *RegisterRequest) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *RegisterRequest) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *RegisterRequest) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *RegisterRequest) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *RegisterRequest) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *RegisterRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RegisterRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *RegisterRequest) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type RegisterCustomerRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,5,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,7,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,9,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,10,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,11,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,12,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,13,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,16,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	UserID               string   `protobuf:"bytes,17,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(m, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *RegisterCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterCustomerRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegisterCustomerRequest) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *RegisterCustomerRequest) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *RegisterCustomerRequest) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *RegisterCustomerRequest) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *RegisterCustomerRequest) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *RegisterCustomerRequest) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *RegisterCustomerRequest) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *RegisterCustomerRequest) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *RegisterCustomerRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RegisterCustomerRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *RegisterCustomerRequest) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

func (m *RegisterCustomerRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type RegisterCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{5}
}

func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(m, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

type LoginCustomerRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCustomerRequest) Reset()         { *m = LoginCustomerRequest{} }
func (m *LoginCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*LoginCustomerRequest) ProtoMessage()    {}
func (*LoginCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{6}
}

func (m *LoginCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCustomerRequest.Unmarshal(m, b)
}
func (m *LoginCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCustomerRequest.Marshal(b, m, deterministic)
}
func (m *LoginCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCustomerRequest.Merge(m, src)
}
func (m *LoginCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_LoginCustomerRequest.Size(m)
}
func (m *LoginCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCustomerRequest proto.InternalMessageInfo

func (m *LoginCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginCustomerResponse struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,6,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,8,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,9,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,10,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,11,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,12,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,13,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,16,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	UserID               string   `protobuf:"bytes,17,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCustomerResponse) Reset()         { *m = LoginCustomerResponse{} }
func (m *LoginCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*LoginCustomerResponse) ProtoMessage()    {}
func (*LoginCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{7}
}

func (m *LoginCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCustomerResponse.Unmarshal(m, b)
}
func (m *LoginCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCustomerResponse.Marshal(b, m, deterministic)
}
func (m *LoginCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCustomerResponse.Merge(m, src)
}
func (m *LoginCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_LoginCustomerResponse.Size(m)
}
func (m *LoginCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCustomerResponse proto.InternalMessageInfo

func (m *LoginCustomerResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *LoginCustomerResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginCustomerResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginCustomerResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginCustomerResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *LoginCustomerResponse) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *LoginCustomerResponse) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *LoginCustomerResponse) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *LoginCustomerResponse) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *LoginCustomerResponse) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *LoginCustomerResponse) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *LoginCustomerResponse) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *LoginCustomerResponse) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *LoginCustomerResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LoginCustomerResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *LoginCustomerResponse) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

func (m *LoginCustomerResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type LoginAdminRequest struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminRequest) Reset()         { *m = LoginAdminRequest{} }
func (m *LoginAdminRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAdminRequest) ProtoMessage()    {}
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{8}
}

func (m *LoginAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminRequest.Unmarshal(m, b)
}
func (m *LoginAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminRequest.Marshal(b, m, deterministic)
}
func (m *LoginAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminRequest.Merge(m, src)
}
func (m *LoginAdminRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAdminRequest.Size(m)
}
func (m *LoginAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminRequest proto.InternalMessageInfo

func (m *LoginAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAdminResponse struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,6,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,8,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,9,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,10,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,11,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,12,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,13,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,16,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	UserID               string   `protobuf:"bytes,17,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminResponse) Reset()         { *m = LoginAdminResponse{} }
func (m *LoginAdminResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAdminResponse) ProtoMessage()    {}
func (*LoginAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{9}
}

func (m *LoginAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminResponse.Unmarshal(m, b)
}
func (m *LoginAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminResponse.Marshal(b, m, deterministic)
}
func (m *LoginAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminResponse.Merge(m, src)
}
func (m *LoginAdminResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAdminResponse.Size(m)
}
func (m *LoginAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminResponse proto.InternalMessageInfo

func (m *LoginAdminResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *LoginAdminResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAdminResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginAdminResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginAdminResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *LoginAdminResponse) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *LoginAdminResponse) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *LoginAdminResponse) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *LoginAdminResponse) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *LoginAdminResponse) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *LoginAdminResponse) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *LoginAdminResponse) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *LoginAdminResponse) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *LoginAdminResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *LoginAdminResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *LoginAdminResponse) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

func (m *LoginAdminResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ForgotPasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{10}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ForgotPasswordResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11}
}

func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(m, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

func (m *ForgotPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyOTPRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp                  string   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPRequest) Reset()         { *m = VerifyOTPRequest{} }
func (m *VerifyOTPRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPRequest) ProtoMessage()    {}
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{12}
}

func (m *VerifyOTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPRequest.Unmarshal(m, b)
}
func (m *VerifyOTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPRequest.Marshal(b, m, deterministic)
}
func (m *VerifyOTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPRequest.Merge(m, src)
}
func (m *VerifyOTPRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPRequest.Size(m)
}
func (m *VerifyOTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPRequest proto.InternalMessageInfo

func (m *VerifyOTPRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *VerifyOTPRequest) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

type VerifyOTPResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPResponse) Reset()         { *m = VerifyOTPResponse{} }
func (m *VerifyOTPResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPResponse) ProtoMessage()    {}
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{13}
}

func (m *VerifyOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPResponse.Unmarshal(m, b)
}
func (m *VerifyOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPResponse.Marshal(b, m, deterministic)
}
func (m *VerifyOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPResponse.Merge(m, src)
}
func (m *VerifyOTPResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPResponse.Size(m)
}
func (m *VerifyOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPResponse proto.InternalMessageInfo

type ResetPasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{14}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{15}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type ChangePasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{16}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{17}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*RegisterCustomerRequest)(nil), "auth.RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "auth.RegisterCustomerResponse")
	proto.RegisterType((*LoginCustomerRequest)(nil), "auth.LoginCustomerRequest")
	proto.RegisterType((*LoginCustomerResponse)(nil), "auth.LoginCustomerResponse")
	proto.RegisterType((*LoginAdminRequest)(nil), "auth.LoginAdminRequest")
	proto.RegisterType((*LoginAdminResponse)(nil), "auth.LoginAdminResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "auth.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "auth.ForgotPasswordResponse")
	proto.RegisterType((*VerifyOTPRequest)(nil), "auth.VerifyOTPRequest")
	proto.RegisterType((*VerifyOTPResponse)(nil), "auth.VerifyOTPResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "auth.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "auth.ResetPasswordResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "auth.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "auth.ChangePasswordResponse")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x98, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe5, 0xc4, 0x49, 0x93, 0x27, 0x2f, 0x9b, 0x4c, 0xf3, 0x32, 0xeb, 0xa6, 0xdb, 0xc8,
	0x4b, 0x51, 0x84, 0x96, 0x44, 0x2c, 0x17, 0xc4, 0xad, 0x69, 0x41, 0xaa, 0x40, 0x62, 0xe5, 0xb2,
	0x8b, 0x04, 0x12, 0xad, 0x13, 0x4f, 0x53, 0xb3, 0x8e, 0xc7, 0xd8, 0x93, 0xb6, 0x2b, 0x2e, 0x68,
	0xb9, 0x21, 0x71, 0x42, 0xe2, 0x33, 0xf0, 0x7d, 0xf8, 0x0a, 0xf0, 0x25, 0x7a, 0x42, 0x1e, 0x8f,
	0x1d, 0xdb, 0x71, 0xd2, 0x16, 0x4e, 0xab, 0xdd, 0xdb, 0xf8, 0xf9, 0x8f, 0x9f, 0xff, 0x33, 0x33,
	0xbf, 0x78, 0x66, 0x02, 0x0d, 0xc7, 0xa5, 0x8c, 0x8e, 0xf4, 0x05, 0xbb, 0x18, 0xf2, 0x26, 0x92,
	0xfd, 0xb6, 0xd2, 0x9b, 0x51, 0x3a, 0xb3, 0xc8, 0x48, 0x77, 0xcc, 0x91, 0x6e, 0xdb, 0x94, 0xe9,
	0xcc, 0xa4, 0xb6, 0x17, 0xf4, 0x51, 0xba, 0x97, 0xba, 0x65, 0x1a, 0x3a, 0x23, 0xa3, 0xb0, 0x21,
	0x04, 0x91, 0x8e, 0xd8, 0x8b, 0x79, 0x10, 0x51, 0x5f, 0x40, 0xf5, 0x4b, 0x3a, 0x33, 0x6d, 0x8d,
	0xfc, 0xb8, 0x20, 0x1e, 0x43, 0x7b, 0x50, 0x70, 0x2e, 0xa8, 0x4d, 0xb0, 0xd4, 0x97, 0x06, 0xe5,
	0x71, 0xf9, 0x66, 0x5c, 0x74, 0xe5, 0x06, 0xe0, 0x8a, 0x16, 0xc4, 0xd1, 0x3e, 0x94, 0x1c, 0xdd,
	0xf3, 0xae, 0xa8, 0x6b, 0xe0, 0x7c, 0xbc, 0x4f, 0x11, 0xb7, 0xb4, 0x48, 0x52, 0xff, 0xc9, 0x43,
	0x4d, 0x24, 0xf6, 0x1c, 0x6a, 0x7b, 0x04, 0x29, 0x50, 0x3a, 0x5f, 0x58, 0x96, 0xad, 0xcf, 0x45,
	0x72, 0x2d, 0x7a, 0x46, 0xad, 0xd0, 0x95, 0x67, 0x0c, 0xad, 0x5a, 0x50, 0x60, 0xf4, 0x25, 0xb1,
	0xb1, 0x1c, 0x44, 0xf9, 0x03, 0x6a, 0x40, 0x5e, 0x9f, 0x11, 0x5c, 0xe8, 0x4b, 0x83, 0x82, 0xe6,
	0x37, 0xd1, 0x63, 0xa8, 0x99, 0x06, 0xb1, 0x99, 0xc9, 0x5e, 0x9d, 0x4e, 0x75, 0xd7, 0xc0, 0x45,
	0xde, 0xbf, 0x1a, 0x06, 0x0f, 0x75, 0xd7, 0xf0, 0x5f, 0xfb, 0x81, 0x4e, 0xf0, 0x16, 0x97, 0xfc,
	0x26, 0xda, 0x07, 0xd9, 0xa5, 0x16, 0xc1, 0xa5, 0xbe, 0x34, 0xa8, 0x3f, 0x6d, 0x0e, 0xfd, 0x59,
	0x39, 0x75, 0x26, 0xc3, 0xe7, 0x1e, 0x71, 0x35, 0x6a, 0x11, 0x8d, 0xcb, 0x48, 0x85, 0xbc, 0x47,
	0xae, 0x71, 0x99, 0xf7, 0x6a, 0x24, 0x7a, 0x9d, 0x90, 0x6b, 0xcd, 0x17, 0xd1, 0x23, 0x00, 0xc7,
	0xa5, 0x97, 0xa6, 0x3d, 0x25, 0xc7, 0x47, 0x18, 0x78, 0x69, 0xb1, 0x88, 0xaf, 0x1b, 0xa6, 0xc7,
	0x5c, 0x73, 0xca, 0x8e, 0x8f, 0x70, 0x25, 0xd0, 0x97, 0x11, 0xd4, 0x81, 0xe2, 0x95, 0xee, 0x1a,
	0xc7, 0x47, 0xb8, 0xca, 0x35, 0xf1, 0x84, 0xde, 0x83, 0x9a, 0x45, 0xa7, 0x7c, 0x6d, 0x4f, 0xa6,
	0xd4, 0x25, 0xb8, 0xd6, 0x97, 0x06, 0x79, 0x2d, 0x19, 0x44, 0x3d, 0x28, 0x4f, 0x5d, 0xa2, 0x33,
	0x62, 0x1c, 0x30, 0x5c, 0xe7, 0x03, 0x5c, 0x06, 0x7c, 0x75, 0xe1, 0x18, 0x42, 0x7d, 0x10, 0xa8,
	0x51, 0x00, 0xbd, 0x0f, 0xf5, 0x89, 0x45, 0xa7, 0x2f, 0x89, 0xe1, 0x0f, 0xe8, 0xf8, 0xc8, 0xc3,
	0x8d, 0x7e, 0x7e, 0x50, 0xd6, 0x52, 0x51, 0xbf, 0xc2, 0x05, 0x6f, 0xe2, 0x26, 0x4f, 0x21, 0x9e,
	0xd4, 0x5f, 0x65, 0x78, 0xa0, 0x91, 0x99, 0xe9, 0x31, 0xe2, 0x86, 0x0c, 0xed, 0xa7, 0x57, 0x3a,
	0x81, 0x48, 0xb4, 0xe8, 0x11, 0x6a, 0xb9, 0xff, 0x85, 0x5a, 0x08, 0x84, 0xbc, 0x01, 0x88, 0xc2,
	0x7a, 0x20, 0x8a, 0x4b, 0x20, 0x46, 0x02, 0x88, 0xad, 0x35, 0x40, 0x8c, 0x4b, 0x37, 0xe3, 0xc2,
	0x6b, 0x29, 0xd7, 0x90, 0x04, 0x1a, 0x4f, 0x02, 0x34, 0x4a, 0xd9, 0x68, 0xc4, 0xba, 0x67, 0x40,
	0x52, 0xbe, 0x05, 0x12, 0xd8, 0x00, 0x49, 0x65, 0x33, 0x24, 0xd5, 0x5b, 0x21, 0xa9, 0x6d, 0x84,
	0xa4, 0x7e, 0x3b, 0x24, 0x0f, 0xb2, 0x20, 0x51, 0x11, 0x34, 0x96, 0x2c, 0x04, 0x3f, 0x7b, 0xf5,
	0x4f, 0x19, 0xba, 0x61, 0xf0, 0x70, 0xe1, 0x31, 0x3a, 0xbf, 0x37, 0x28, 0xbb, 0x50, 0x20, 0x73,
	0xdd, 0xb4, 0x04, 0x28, 0x5b, 0x37, 0x63, 0xd9, 0xcd, 0x9d, 0x49, 0x5a, 0x10, 0x7d, 0x63, 0x30,
	0x29, 0xff, 0x17, 0x4c, 0xde, 0xa6, 0x6f, 0x89, 0x02, 0x78, 0x95, 0x14, 0x81, 0xd1, 0xf7, 0xd0,
	0xe2, 0xdb, 0x49, 0x1a, 0xa1, 0xbd, 0x90, 0x8d, 0x15, 0x7e, 0x32, 0xe8, 0xc8, 0xad, 0xdf, 0xaf,
	0x7e, 0x91, 0xa1, 0x9d, 0x32, 0xb8, 0xdb, 0xbe, 0x15, 0x23, 0x33, 0xb4, 0x7c, 0xb7, 0x9b, 0xbd,
	0xa9, 0x04, 0x7e, 0x07, 0x4d, 0x0e, 0xc1, 0x81, 0x31, 0x4f, 0x1c, 0x89, 0xe2, 0x9f, 0x9f, 0xcd,
	0x88, 0x6d, 0x38, 0x12, 0xfd, 0x2c, 0x03, 0x8a, 0x67, 0x7f, 0xc7, 0xd7, 0x5b, 0xc7, 0xd7, 0x27,
	0xd0, 0xfe, 0x9c, 0xba, 0x33, 0xca, 0x9e, 0x09, 0x28, 0xee, 0x7a, 0xec, 0x56, 0x87, 0xd0, 0x49,
	0xbf, 0x29, 0xf8, 0x89, 0xd6, 0x5d, 0x8a, 0xad, 0xbb, 0xfa, 0x19, 0x34, 0x5e, 0x10, 0xd7, 0x3c,
	0x7f, 0xf5, 0xd5, 0xd7, 0xcf, 0xee, 0x7c, 0xb6, 0x6f, 0x40, 0x9e, 0x32, 0x47, 0xc0, 0xe6, 0x37,
	0xd5, 0x6d, 0x68, 0xc6, 0xd2, 0x88, 0x6f, 0xf1, 0x4f, 0xd0, 0xd2, 0x88, 0x47, 0xee, 0x3d, 0x88,
	0x65, 0xa9, 0xb9, 0x38, 0xa2, 0x4f, 0xa0, 0x6a, 0x93, 0xab, 0xd3, 0xf5, 0x3f, 0xa1, 0x8a, 0x4d,
	0xae, 0x42, 0x2f, 0xb5, 0x0b, 0xed, 0x94, 0xb9, 0xa8, 0xea, 0x37, 0x09, 0xda, 0x87, 0x17, 0xba,
	0x3d, 0x23, 0xf7, 0xae, 0xeb, 0x6e, 0x7b, 0xc4, 0x3d, 0x0b, 0xc5, 0xd0, 0x49, 0x97, 0x13, 0x54,
	0xfa, 0xf4, 0x8f, 0x2d, 0xa8, 0x1c, 0x2c, 0xd8, 0xc5, 0x09, 0x71, 0x2f, 0xcd, 0x29, 0x41, 0x5f,
	0x40, 0x81, 0x7f, 0x17, 0x10, 0x1a, 0xf2, 0x8b, 0x5e, 0xfc, 0x42, 0xa6, 0x6c, 0x27, 0x62, 0x62,
	0xac, 0x0f, 0x5f, 0xff, 0xf5, 0xf7, 0xef, 0xb9, 0x6d, 0xb5, 0x3e, 0xba, 0xfc, 0x88, 0x5f, 0x0e,
	0x47, 0x96, 0xaf, 0x7f, 0x2a, 0x7d, 0x80, 0xbe, 0x81, 0x52, 0xb8, 0x89, 0xa2, 0x76, 0xf0, 0x6e,
	0xea, 0x7c, 0xae, 0x74, 0xd2, 0x61, 0x91, 0xb5, 0xc7, 0xb3, 0x76, 0xd4, 0x66, 0x94, 0xd5, 0x15,
	0x5d, 0xfc, 0xc4, 0x0e, 0xd4, 0x93, 0x04, 0xa2, 0x9d, 0x20, 0x4f, 0x26, 0xd1, 0x4a, 0x2f, 0x5b,
	0x14, 0x56, 0x8f, 0xb9, 0xd5, 0xae, 0x8a, 0x23, 0xab, 0x73, 0xde, 0xf1, 0xc3, 0x70, 0x72, 0x7d,
	0xc7, 0xe7, 0x50, 0x8e, 0xe0, 0x43, 0xa2, 0xe8, 0x34, 0xd4, 0x4a, 0x77, 0x25, 0x2e, 0x2c, 0xba,
	0xdc, 0xa2, 0xa9, 0x56, 0x23, 0x0b, 0xca, 0x1c, 0x3f, 0xad, 0x05, 0xb5, 0x04, 0x41, 0x48, 0x09,
	0xe7, 0x63, 0x95, 0x69, 0x65, 0x27, 0x53, 0x13, 0x16, 0x2a, 0xb7, 0xe8, 0xa9, 0xdd, 0xd8, 0x84,
	0x79, 0x24, 0x39, 0x88, 0x33, 0xa8, 0x27, 0x31, 0x08, 0xa7, 0x2d, 0x93, 0xd5, 0x70, 0xda, 0xb2,
	0xc9, 0x51, 0xb7, 0xb9, 0x61, 0x4d, 0x29, 0x85, 0x86, 0xbe, 0xc3, 0xf5, 0xf2, 0xd4, 0x1d, 0x1e,
	0x5e, 0xd0, 0x6e, 0x72, 0x89, 0x53, 0xa7, 0x26, 0xe5, 0xd1, 0x3a, 0x59, 0xf8, 0xec, 0x73, 0x9f,
	0x3d, 0x55, 0x89, 0x06, 0x36, 0x15, 0x5d, 0x12, 0x48, 0x58, 0xe2, 0x8e, 0x1f, 0xd9, 0x2a, 0x31,
	0x58, 0xd3, 0x9e, 0x3b, 0x99, 0xda, 0xda, 0x99, 0x8c, 0x0c, 0x23, 0xb2, 0xcf, 0x00, 0x96, 0xdb,
	0x27, 0xea, 0xc6, 0xd2, 0xc5, 0xb7, 0x6b, 0x05, 0xaf, 0x0a, 0xc2, 0x64, 0x8f, 0x9b, 0x3c, 0x54,
	0x5b, 0x91, 0x89, 0xee, 0xeb, 0x91, 0xc3, 0xb8, 0xf8, 0xad, 0x3c, 0x1c, 0x39, 0x93, 0x49, 0x91,
	0xff, 0x37, 0xf2, 0xf1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x53, 0x91, 0x47, 0x7e, 0x11,
	0x00, 0x00,
}
