// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package pb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterCustomerRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(m, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *RegisterCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(m, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

type LoginCustomerRequest struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCustomerRequest) Reset()         { *m = LoginCustomerRequest{} }
func (m *LoginCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*LoginCustomerRequest) ProtoMessage()    {}
func (*LoginCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *LoginCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCustomerRequest.Unmarshal(m, b)
}
func (m *LoginCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCustomerRequest.Marshal(b, m, deterministic)
}
func (m *LoginCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCustomerRequest.Merge(m, src)
}
func (m *LoginCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_LoginCustomerRequest.Size(m)
}
func (m *LoginCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCustomerRequest proto.InternalMessageInfo

func (m *LoginCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginCustomerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginCustomerResponse struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginCustomerResponse) Reset()         { *m = LoginCustomerResponse{} }
func (m *LoginCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*LoginCustomerResponse) ProtoMessage()    {}
func (*LoginCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *LoginCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginCustomerResponse.Unmarshal(m, b)
}
func (m *LoginCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginCustomerResponse.Marshal(b, m, deterministic)
}
func (m *LoginCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCustomerResponse.Merge(m, src)
}
func (m *LoginCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_LoginCustomerResponse.Size(m)
}
func (m *LoginCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCustomerResponse proto.InternalMessageInfo

func (m *LoginCustomerResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *LoginCustomerResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginCustomerResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ForgotPasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ForgotPasswordResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{5}
}

func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(m, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

func (m *ForgotPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyOTPRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp                  string   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPRequest) Reset()         { *m = VerifyOTPRequest{} }
func (m *VerifyOTPRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPRequest) ProtoMessage()    {}
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{6}
}

func (m *VerifyOTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPRequest.Unmarshal(m, b)
}
func (m *VerifyOTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPRequest.Marshal(b, m, deterministic)
}
func (m *VerifyOTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPRequest.Merge(m, src)
}
func (m *VerifyOTPRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPRequest.Size(m)
}
func (m *VerifyOTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPRequest proto.InternalMessageInfo

func (m *VerifyOTPRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *VerifyOTPRequest) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

type VerifyOTPResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPResponse) Reset()         { *m = VerifyOTPResponse{} }
func (m *VerifyOTPResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPResponse) ProtoMessage()    {}
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{7}
}

func (m *VerifyOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPResponse.Unmarshal(m, b)
}
func (m *VerifyOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPResponse.Marshal(b, m, deterministic)
}
func (m *VerifyOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPResponse.Merge(m, src)
}
func (m *VerifyOTPResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPResponse.Size(m)
}
func (m *VerifyOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPResponse proto.InternalMessageInfo

type ResetPasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{8}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{9}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type ChangePasswordRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{10}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterCustomerRequest)(nil), "auth.RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "auth.RegisterCustomerResponse")
	proto.RegisterType((*LoginCustomerRequest)(nil), "auth.LoginCustomerRequest")
	proto.RegisterType((*LoginCustomerResponse)(nil), "auth.LoginCustomerResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "auth.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "auth.ForgotPasswordResponse")
	proto.RegisterType((*VerifyOTPRequest)(nil), "auth.VerifyOTPRequest")
	proto.RegisterType((*VerifyOTPResponse)(nil), "auth.VerifyOTPResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "auth.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "auth.ResetPasswordResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "auth.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "auth.ChangePasswordResponse")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe5, 0xac, 0x2b, 0xec, 0x15, 0xa4, 0x60, 0xd2, 0x35, 0x0a, 0x1b, 0x43, 0x96, 0x26,
	0xa1, 0x09, 0x35, 0x02, 0x2e, 0x68, 0x37, 0x3a, 0xc1, 0x09, 0x89, 0x29, 0x20, 0x0e, 0x1c, 0x18,
	0xde, 0xf6, 0x96, 0x46, 0xa4, 0x76, 0xb0, 0x9d, 0x16, 0xc4, 0x8d, 0x03, 0x37, 0x4e, 0x7c, 0x34,
	0xbe, 0x02, 0x5f, 0x81, 0xcb, 0x4e, 0xa8, 0xb1, 0x3b, 0xd2, 0xb4, 0x95, 0xd6, 0xdb, 0x4b, 0x9e,
	0xfd, 0xff, 0xfd, 0x9f, 0xfd, 0x9e, 0xc1, 0x2f, 0x94, 0x34, 0x32, 0xe6, 0xa5, 0x19, 0xf6, 0xab,
	0x90, 0xb6, 0xa6, 0x71, 0xb4, 0x93, 0x4a, 0x99, 0xe6, 0x18, 0xf3, 0x22, 0x8b, 0xb9, 0x10, 0xd2,
	0x70, 0x93, 0x49, 0xa1, 0xed, 0x9a, 0xa8, 0x37, 0xe6, 0x79, 0x76, 0xce, 0x0d, 0xc6, 0xb3, 0xc0,
	0x26, 0xd8, 0x0f, 0x02, 0xbd, 0x04, 0xd3, 0x4c, 0x1b, 0x54, 0x47, 0xa5, 0x36, 0x72, 0x84, 0x2a,
	0xc1, 0xcf, 0x25, 0x6a, 0x43, 0xf7, 0xe1, 0xe6, 0x45, 0x99, 0xe7, 0x82, 0x8f, 0x30, 0x24, 0x0f,
	0xc8, 0xc3, 0xad, 0xc1, 0xd6, 0xe5, 0xa0, 0xad, 0x5a, 0x7e, 0x3b, 0x0c, 0x92, 0xab, 0x14, 0xdd,
	0x85, 0x4d, 0x1c, 0xf1, 0x2c, 0x0f, 0xbd, 0x6a, 0xcd, 0x8d, 0xcb, 0x41, 0x4b, 0x79, 0x1f, 0x49,
	0x62, 0xff, 0x4e, 0x55, 0x0a, 0xae, 0xf5, 0x44, 0xaa, 0xf3, 0x70, 0x63, 0x41, 0x65, 0x96, 0x62,
	0x11, 0x84, 0x8b, 0x3e, 0x74, 0x21, 0x85, 0x46, 0xf6, 0x01, 0x82, 0x57, 0x32, 0xcd, 0x44, 0xd3,
	0xe0, 0xde, 0x3c, 0xb9, 0xa6, 0xbb, 0x1e, 0xfb, 0x04, 0xba, 0x0d, 0x7d, 0x0b, 0xa6, 0x51, 0xf3,
	0x04, 0x6a, 0x65, 0x07, 0x73, 0xf0, 0x19, 0x31, 0x80, 0x4d, 0x23, 0x3f, 0xa1, 0xb0, 0xb8, 0xc4,
	0x7e, 0xb0, 0x67, 0xd0, 0x7d, 0x29, 0x55, 0x2a, 0xcd, 0xb1, 0x43, 0xd6, 0x2a, 0x28, 0x86, 0x52,
	0x34, 0xce, 0x17, 0xc2, 0x4e, 0x62, 0xff, 0xb3, 0x3e, 0x6c, 0x37, 0x77, 0x3a, 0x6f, 0x57, 0x24,
	0x52, 0x27, 0xbd, 0x00, 0xff, 0x1d, 0xaa, 0xec, 0xe2, 0xeb, 0xeb, 0xb7, 0xc7, 0xd7, 0x85, 0x50,
	0x1f, 0x36, 0xa4, 0x29, 0x5c, 0x21, 0xd3, 0x90, 0xdd, 0x85, 0x3b, 0x35, 0x19, 0x77, 0x0d, 0xdf,
	0x20, 0x48, 0x50, 0xe3, 0xda, 0x45, 0xfc, 0xb7, 0xea, 0xd5, 0xac, 0xd2, 0x47, 0x70, 0x4b, 0xe0,
	0xe4, 0x64, 0xf5, 0x05, 0x75, 0x04, 0x4e, 0x66, 0x2c, 0xd6, 0x83, 0x6e, 0x03, 0xee, 0x5c, 0xfd,
	0x24, 0xd0, 0x3d, 0x1a, 0x72, 0x91, 0xe2, 0xda, 0xbe, 0xea, 0xed, 0xe1, 0xad, 0x6c, 0x8f, 0x35,
	0x8d, 0x86, 0xb0, 0xdd, 0xb4, 0x63, 0x9d, 0x3e, 0xf9, 0x4b, 0xa0, 0xf3, 0xbc, 0x34, 0xc3, 0x37,
	0xa8, 0xc6, 0xd9, 0x19, 0xd2, 0x2f, 0xe0, 0x37, 0x5b, 0x9e, 0xee, 0xf6, 0xab, 0xc9, 0x5e, 0x31,
	0x92, 0xd1, 0xfd, 0x55, 0x69, 0x77, 0x18, 0xfb, 0xdf, 0x7f, 0xff, 0xf9, 0xe5, 0xed, 0xb1, 0x28,
	0x1e, 0x3f, 0xae, 0xde, 0x88, 0xf8, 0xcc, 0x2d, 0x89, 0x95, 0xdb, 0x73, 0x48, 0x0e, 0x68, 0x0e,
	0xb7, 0xe7, 0x1a, 0x9e, 0x46, 0x56, 0x77, 0xd9, 0x94, 0x45, 0xf7, 0x96, 0xe6, 0x1c, 0x90, 0x55,
	0xc0, 0x1d, 0xd6, 0x5b, 0x04, 0xe6, 0xd3, 0x0d, 0x87, 0xe4, 0x60, 0xd0, 0x7e, 0xdf, 0xea, 0xc7,
	0xc5, 0xe9, 0x69, 0xbb, 0x7a, 0x72, 0x9e, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x49, 0x94,
	0xc0, 0xc3, 0x04, 0x00, 0x00,
}
