// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	ImageUrl             string   `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	CategoryId           string   `protobuf:"bytes,7,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Product) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Product) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Product) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type CreateProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	CategoryId           string   `protobuf:"bytes,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{1}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *CreateProductRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type CreateProductReponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductReponse) Reset()         { *m = CreateProductReponse{} }
func (m *CreateProductReponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductReponse) ProtoMessage()    {}
func (*CreateProductReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{2}
}

func (m *CreateProductReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductReponse.Unmarshal(m, b)
}
func (m *CreateProductReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductReponse.Marshal(b, m, deterministic)
}
func (m *CreateProductReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductReponse.Merge(m, src)
}
func (m *CreateProductReponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductReponse.Size(m)
}
func (m *CreateProductReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductReponse proto.InternalMessageInfo

func (m *CreateProductReponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{3}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

type GetProductsReponse struct {
	Product              []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsReponse) Reset()         { *m = GetProductsReponse{} }
func (m *GetProductsReponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsReponse) ProtoMessage()    {}
func (*GetProductsReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{4}
}

func (m *GetProductsReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsReponse.Unmarshal(m, b)
}
func (m *GetProductsReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsReponse.Marshal(b, m, deterministic)
}
func (m *GetProductsReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsReponse.Merge(m, src)
}
func (m *GetProductsReponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsReponse.Size(m)
}
func (m *GetProductsReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsReponse proto.InternalMessageInfo

func (m *GetProductsReponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{5}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type GetProductReponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReponse) Reset()         { *m = GetProductReponse{} }
func (m *GetProductReponse) String() string { return proto.CompactTextString(m) }
func (*GetProductReponse) ProtoMessage()    {}
func (*GetProductReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{6}
}

func (m *GetProductReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReponse.Unmarshal(m, b)
}
func (m *GetProductReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReponse.Marshal(b, m, deterministic)
}
func (m *GetProductReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReponse.Merge(m, src)
}
func (m *GetProductReponse) XXX_Size() int {
	return xxx_messageInfo_GetProductReponse.Size(m)
}
func (m *GetProductReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReponse proto.InternalMessageInfo

func (m *GetProductReponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	CategoryId           string   `protobuf:"bytes,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	ProductId            string   `protobuf:"bytes,4,opt,name=productId,proto3" json:"productId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{7}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductRequest) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *UpdateProductRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *UpdateProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type UpdateProductResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{8}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DeleteProductReponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductReponse) Reset()         { *m = DeleteProductReponse{} }
func (m *DeleteProductReponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductReponse) ProtoMessage()    {}
func (*DeleteProductReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{9}
}

func (m *DeleteProductReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductReponse.Unmarshal(m, b)
}
func (m *DeleteProductReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductReponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductReponse.Merge(m, src)
}
func (m *DeleteProductReponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductReponse.Size(m)
}
func (m *DeleteProductReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductReponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductReponse proto.InternalMessageInfo

func (m *DeleteProductReponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetProductByCategoryRequest struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductByCategoryRequest) Reset()         { *m = GetProductByCategoryRequest{} }
func (m *GetProductByCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductByCategoryRequest) ProtoMessage()    {}
func (*GetProductByCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{10}
}

func (m *GetProductByCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByCategoryRequest.Unmarshal(m, b)
}
func (m *GetProductByCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetProductByCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByCategoryRequest.Merge(m, src)
}
func (m *GetProductByCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductByCategoryRequest.Size(m)
}
func (m *GetProductByCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByCategoryRequest proto.InternalMessageInfo

func (m *GetProductByCategoryRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

type GetProductByCategoryReponse struct {
	Message              string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Product              []*Product `protobuf:"bytes,2,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductByCategoryReponse) Reset()         { *m = GetProductByCategoryReponse{} }
func (m *GetProductByCategoryReponse) String() string { return proto.CompactTextString(m) }
func (*GetProductByCategoryReponse) ProtoMessage()    {}
func (*GetProductByCategoryReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{11}
}

func (m *GetProductByCategoryReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByCategoryReponse.Unmarshal(m, b)
}
func (m *GetProductByCategoryReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByCategoryReponse.Marshal(b, m, deterministic)
}
func (m *GetProductByCategoryReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByCategoryReponse.Merge(m, src)
}
func (m *GetProductByCategoryReponse) XXX_Size() int {
	return xxx_messageInfo_GetProductByCategoryReponse.Size(m)
}
func (m *GetProductByCategoryReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByCategoryReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByCategoryReponse proto.InternalMessageInfo

func (m *GetProductByCategoryReponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetProductByCategoryReponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "pb.Product")
	proto.RegisterType((*CreateProductRequest)(nil), "pb.CreateProductRequest")
	proto.RegisterType((*CreateProductReponse)(nil), "pb.CreateProductReponse")
	proto.RegisterType((*GetProductsRequest)(nil), "pb.GetProductsRequest")
	proto.RegisterType((*GetProductsReponse)(nil), "pb.GetProductsReponse")
	proto.RegisterType((*GetProductRequest)(nil), "pb.GetProductRequest")
	proto.RegisterType((*GetProductReponse)(nil), "pb.GetProductReponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "pb.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "pb.UpdateProductResponse")
	proto.RegisterType((*DeleteProductReponse)(nil), "pb.DeleteProductReponse")
	proto.RegisterType((*GetProductByCategoryRequest)(nil), "pb.GetProductByCategoryRequest")
	proto.RegisterType((*GetProductByCategoryReponse)(nil), "pb.GetProductByCategoryReponse")
}

func init() { proto.RegisterFile("proto/product.proto", fileDescriptor_cfd9ed8e6077aee0) }

var fileDescriptor_cfd9ed8e6077aee0 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x9d, 0x34, 0xa1, 0xb7, 0x24, 0x52, 0x2f, 0x49, 0x19, 0x99, 0x42, 0x83, 0x11, 0xa2,
	0x14, 0x35, 0x56, 0xca, 0xae, 0xa8, 0x9b, 0x16, 0x09, 0x75, 0x87, 0x52, 0x75, 0x83, 0x2a, 0x24,
	0x27, 0x1e, 0x8c, 0xa5, 0x24, 0x36, 0x9e, 0x49, 0xa5, 0xa8, 0xea, 0x06, 0xc1, 0x8e, 0x1d, 0x5f,
	0xc2, 0xb7, 0xf0, 0x0b, 0x7c, 0x08, 0xf2, 0x3c, 0x62, 0x4f, 0x1c, 0x57, 0x62, 0xc1, 0xce, 0xf7,
	0x75, 0xce, 0xb9, 0x77, 0x4e, 0x1b, 0x78, 0x90, 0xa4, 0x31, 0x8f, 0xbd, 0x24, 0x8d, 0x83, 0xf9,
	0x98, 0xf7, 0x45, 0x84, 0x76, 0x32, 0x72, 0x76, 0xc3, 0x38, 0x0e, 0x27, 0xd4, 0xf3, 0x93, 0xc8,
	0xf3, 0x67, 0xb3, 0x98, 0xfb, 0x3c, 0x8a, 0x67, 0x4c, 0x76, 0xb8, 0xbf, 0x2c, 0x68, 0xbe, 0x97,
	0x33, 0xd8, 0x06, 0x3b, 0x0a, 0x88, 0xd5, 0xb3, 0xf6, 0x37, 0x87, 0x76, 0x14, 0x20, 0x42, 0x7d,
	0xe6, 0x4f, 0x29, 0xb1, 0x45, 0x46, 0x7c, 0x67, 0x39, 0x36, 0x99, 0x87, 0xa4, 0x26, 0x73, 0xd9,
	0x37, 0x12, 0x68, 0x8e, 0x53, 0xea, 0x73, 0x1a, 0x90, 0x7a, 0xcf, 0xda, 0xaf, 0x0d, 0x75, 0x98,
	0x55, 0xe6, 0x49, 0x20, 0x2a, 0x1b, 0xb2, 0xa2, 0x42, 0x74, 0xe0, 0x5e, 0x34, 0xf5, 0x43, 0x7a,
	0x99, 0x4e, 0x48, 0x43, 0x60, 0x2d, 0x63, 0x7c, 0x02, 0x30, 0xf6, 0x39, 0x0d, 0xe3, 0x74, 0x71,
	0x1e, 0x90, 0xa6, 0xa8, 0x16, 0x32, 0xee, 0x27, 0xe8, 0x9c, 0x09, 0x02, 0x25, 0x7c, 0x48, 0xbf,
	0xcc, 0x29, 0xe3, 0x4b, 0xbd, 0x56, 0x41, 0x6f, 0x91, 0xc7, 0xbe, 0x93, 0xa7, 0x56, 0xe2, 0x39,
	0x29, 0xf1, 0x24, 0xf1, 0x8c, 0x51, 0x7c, 0x0e, 0x4d, 0x75, 0x66, 0x41, 0xb5, 0x75, 0xb4, 0xd5,
	0x4f, 0x46, 0x7d, 0xdd, 0xa4, 0x6b, 0x6e, 0x07, 0xf0, 0x1d, 0xe5, 0x2a, 0xcd, 0x94, 0x48, 0xf7,
	0xcd, 0x4a, 0x76, 0x0d, 0x64, 0xad, 0x12, 0x72, 0x00, 0xdb, 0xf9, 0xb0, 0x5e, 0x7b, 0x17, 0x36,
	0x55, 0xfd, 0x5c, 0xbf, 0x5e, 0x9e, 0x70, 0x8f, 0xcd, 0x91, 0x7f, 0xda, 0xe0, 0x9b, 0x05, 0x9d,
	0x4b, 0xf1, 0x60, 0xff, 0xf7, 0xd2, 0xe6, 0x0a, 0xf5, 0xd5, 0x15, 0x3c, 0xe8, 0xae, 0xa8, 0x60,
	0x72, 0x8d, 0x1d, 0x68, 0xa4, 0x94, 0xcd, 0x27, 0x5c, 0x09, 0x51, 0x91, 0xdb, 0x87, 0xce, 0x5b,
	0x3a, 0xa1, 0xa5, 0x87, 0xab, 0xea, 0x3f, 0x81, 0x47, 0xf9, 0x8d, 0x4e, 0x17, 0x67, 0x4a, 0x98,
	0xde, 0xd6, 0x54, 0x6f, 0x95, 0x7c, 0xf2, 0xb1, 0x6a, 0x5c, 0xb2, 0x12, 0x68, 0x4e, 0x29, 0x63,
	0x7e, 0xa8, 0xef, 0xa5, 0xc3, 0xe2, 0x33, 0xd8, 0xd5, 0xaf, 0x7e, 0xf4, 0x7d, 0x03, 0xda, 0x2a,
	0x79, 0x41, 0xd3, 0xeb, 0x68, 0x4c, 0xf1, 0x0a, 0x5a, 0x86, 0x35, 0x91, 0x64, 0x93, 0xeb, 0xfe,
	0x2a, 0x9c, 0x75, 0x15, 0x21, 0xcc, 0x7d, 0xf8, 0xf5, 0xf7, 0x9f, 0x9f, 0xf6, 0xb6, 0x7b, 0xdf,
	0xbb, 0x1e, 0xe8, 0x7f, 0x1c, 0xec, 0xd8, 0x3a, 0xc0, 0x0b, 0xd8, 0x2a, 0x78, 0x14, 0x77, 0x32,
	0x84, 0xb2, 0x95, 0x9d, 0x72, 0x5e, 0xe2, 0x76, 0x04, 0x6e, 0x1b, 0x0d, 0x5c, 0xbc, 0x02, 0xc8,
	0x7b, 0xb1, 0x6b, 0xce, 0x6a, 0xc8, 0x52, 0x5a, 0x22, 0xf6, 0x04, 0xa2, 0x83, 0xa4, 0x88, 0xe8,
	0xdd, 0x2c, 0x2d, 0x72, 0x8b, 0x9f, 0xa1, 0x65, 0x78, 0x44, 0x1e, 0x64, 0x9d, 0x79, 0xe5, 0x41,
	0xd6, 0xf9, 0xc3, 0x7d, 0x26, 0x68, 0x1e, 0x3b, 0x95, 0x34, 0xd9, 0x71, 0x22, 0x68, 0x19, 0xc3,
	0x55, 0xab, 0x54, 0xd3, 0xbc, 0x10, 0x34, 0x4f, 0x0f, 0xf6, 0x0c, 0x9a, 0x40, 0xb4, 0x1a, 0x4b,
	0xfd, 0xb0, 0xa0, 0x5b, 0xb8, 0x6f, 0x6e, 0x2d, 0xdc, 0x33, 0x39, 0x4b, 0x9e, 0x75, 0xee, 0x68,
	0x90, 0x22, 0x06, 0x42, 0xc4, 0x2b, 0x7c, 0x69, 0x88, 0x08, 0x29, 0x3f, 0x1c, 0x2d, 0x0e, 0xb5,
	0xb9, 0xbd, 0x9b, 0xdc, 0xe6, 0xb7, 0xa7, 0x8d, 0x0f, 0xf5, 0xbe, 0x97, 0x8c, 0x46, 0x0d, 0xf1,
	0xd3, 0xf1, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x81, 0x0b, 0xe9, 0x73, 0x06, 0x00,
	0x00,
}
