// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package pb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserByIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIDRequest) Reset()         { *m = GetUserByIDRequest{} }
func (m *GetUserByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDRequest) ProtoMessage()    {}
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *GetUserByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDRequest.Unmarshal(m, b)
}
func (m *GetUserByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDRequest.Merge(m, src)
}
func (m *GetUserByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDRequest.Size(m)
}
func (m *GetUserByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDRequest proto.InternalMessageInfo

func (m *GetUserByIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserByIDResponse struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	IdentityCard         string   `protobuf:"bytes,5,opt,name=identity_card,json=identityCard,proto3" json:"identity_card,omitempty"`
	Job                  string   `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Role                 UserRole `protobuf:"varint,7,opt,name=role,proto3,enum=enum_pb.UserRole" json:"role,omitempty"`
	Sex                  UserSex  `protobuf:"varint,8,opt,name=sex,proto3,enum=enum_pb.UserSex" json:"sex,omitempty"`
	ProvinceID           int32    `protobuf:"varint,9,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
	DistrictID           int32    `protobuf:"varint,10,opt,name=districtID,proto3" json:"districtID,omitempty"`
	WardID               int32    `protobuf:"varint,11,opt,name=wardID,proto3" json:"wardID,omitempty"`
	LocationScore        int64    `protobuf:"varint,12,opt,name=locationScore,proto3" json:"locationScore,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	BlockedUserIDs       []string `protobuf:"bytes,15,rep,name=blockedUserIDs,proto3" json:"blockedUserIDs,omitempty"`
	UserID               string   `protobuf:"bytes,16,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIDResponse) Reset()         { *m = GetUserByIDResponse{} }
func (m *GetUserByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIDResponse) ProtoMessage()    {}
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *GetUserByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIDResponse.Unmarshal(m, b)
}
func (m *GetUserByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIDResponse.Merge(m, src)
}
func (m *GetUserByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIDResponse.Size(m)
}
func (m *GetUserByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIDResponse proto.InternalMessageInfo

func (m *GetUserByIDResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *GetUserByIDResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByIDResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetUserByIDResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GetUserByIDResponse) GetIdentityCard() string {
	if m != nil {
		return m.IdentityCard
	}
	return ""
}

func (m *GetUserByIDResponse) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *GetUserByIDResponse) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_USER_UNKNOWN
}

func (m *GetUserByIDResponse) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_SEX_UNKNOWN
}

func (m *GetUserByIDResponse) GetProvinceID() int32 {
	if m != nil {
		return m.ProvinceID
	}
	return 0
}

func (m *GetUserByIDResponse) GetDistrictID() int32 {
	if m != nil {
		return m.DistrictID
	}
	return 0
}

func (m *GetUserByIDResponse) GetWardID() int32 {
	if m != nil {
		return m.WardID
	}
	return 0
}

func (m *GetUserByIDResponse) GetLocationScore() int64 {
	if m != nil {
		return m.LocationScore
	}
	return 0
}

func (m *GetUserByIDResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserByIDResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *GetUserByIDResponse) GetBlockedUserIDs() []string {
	if m != nil {
		return m.BlockedUserIDs
	}
	return nil
}

func (m *GetUserByIDResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserByIDRequest)(nil), "user.GetUserByIDRequest")
	proto.RegisterType((*GetUserByIDResponse)(nil), "user.GetUserByIDResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0x95, 0x3a, 0x09, 0xcd, 0xa4, 0x09, 0x61, 0xa9, 0x60, 0xb1, 0x2a, 0x64, 0x85, 0x1f,
	0xf9, 0x80, 0x6c, 0x51, 0x9e, 0x80, 0x62, 0x09, 0xf9, 0xea, 0xaa, 0x17, 0x0e, 0x54, 0x6b, 0x7b,
	0x08, 0x0b, 0xce, 0xae, 0xd9, 0x5d, 0x87, 0x56, 0x88, 0x0b, 0xaf, 0xc0, 0xa3, 0xf1, 0x0a, 0xdc,
	0x78, 0x09, 0xb4, 0xbb, 0x6e, 0x9b, 0x40, 0x6f, 0x33, 0xdf, 0x37, 0xfb, 0x3b, 0x03, 0x8b, 0x56,
	0x49, 0x23, 0xd3, 0x4e, 0xa3, 0x4a, 0x5c, 0x48, 0x86, 0x36, 0x0e, 0x8f, 0x56, 0x52, 0xae, 0x1a,
	0x4c, 0x59, 0xcb, 0x53, 0x26, 0x84, 0x34, 0xcc, 0x70, 0x29, 0xb4, 0xaf, 0x09, 0x1f, 0x6e, 0x58,
	0xc3, 0x6b, 0x66, 0x30, 0xbd, 0x0a, 0x7a, 0xd1, 0x6f, 0x87, 0xa2, 0x5b, 0x7b, 0xb2, 0x7c, 0x01,
	0xe4, 0x2d, 0x9a, 0x33, 0x8d, 0xea, 0xe4, 0x32, 0xcf, 0x0a, 0xfc, 0xd2, 0xa1, 0x36, 0xe4, 0x01,
	0x8c, 0xed, 0x31, 0x79, 0x46, 0x07, 0xd1, 0x20, 0x9e, 0x14, 0x7d, 0xb6, 0xfc, 0x13, 0xc0, 0xfd,
	0x9d, 0x72, 0xdd, 0x4a, 0xa1, 0x91, 0x84, 0xb0, 0xff, 0xa1, 0x6b, 0x1a, 0xc1, 0xd6, 0xd8, 0xaf,
	0xb8, 0xce, 0xc9, 0x21, 0x8c, 0x70, 0xcd, 0x78, 0x43, 0xf7, 0x9c, 0xf0, 0x89, 0xa5, 0xed, 0x47,
	0x29, 0x90, 0x06, 0x9e, 0xba, 0x84, 0x2c, 0x20, 0x60, 0x2b, 0xa4, 0xc3, 0x68, 0x10, 0x8f, 0x0a,
	0x1b, 0x92, 0x27, 0x30, 0xe3, 0x35, 0x0a, 0xc3, 0xcd, 0xe5, 0x79, 0xc5, 0x54, 0x4d, 0x47, 0xae,
	0xfe, 0xe0, 0x0a, 0xbe, 0x61, 0xaa, 0xb6, 0xcb, 0x3e, 0xc9, 0x92, 0x8e, 0x9d, 0xb2, 0x21, 0x79,
	0x06, 0x43, 0x25, 0x1b, 0xa4, 0x77, 0xa2, 0x41, 0x3c, 0x3f, 0xbe, 0x97, 0xd8, 0x17, 0x9f, 0xb7,
	0x65, 0x62, 0x6f, 0x5e, 0xc8, 0x06, 0x0b, 0xa7, 0xc9, 0x12, 0x02, 0x8d, 0x17, 0x74, 0xdf, 0x55,
	0x2d, 0x76, 0xaa, 0x4e, 0xf1, 0xa2, 0xb0, 0x92, 0x3c, 0x06, 0x68, 0x95, 0xdc, 0x70, 0x51, 0x61,
	0x9e, 0xd1, 0x89, 0xbb, 0xda, 0x16, 0xb1, 0xbe, 0xe6, 0xda, 0x28, 0x5e, 0x99, 0x3c, 0xa3, 0xe0,
	0xfd, 0x0d, 0xb1, 0x7f, 0xf9, 0x95, 0xa9, 0x3a, 0xcf, 0xe8, 0xd4, 0xb9, 0x3e, 0x23, 0x4f, 0x61,
	0xd6, 0xc8, 0xca, 0xf5, 0xed, 0xb4, 0x92, 0x0a, 0xe9, 0x41, 0x34, 0x88, 0x83, 0x62, 0x17, 0x92,
	0x23, 0x98, 0x54, 0x0a, 0x99, 0xc1, 0xfa, 0xb5, 0xa1, 0x33, 0xf7, 0xc0, 0x1b, 0x60, 0x6d, 0xd7,
	0xd6, 0xbd, 0x9d, 0x7b, 0x7b, 0x0d, 0xc8, 0x73, 0x98, 0x97, 0x8d, 0xac, 0x3e, 0x63, 0x7d, 0xe6,
	0xda, 0xa7, 0xe9, 0xdd, 0x28, 0x88, 0x27, 0xc5, 0x3f, 0x74, 0xab, 0xdb, 0x8b, 0xed, 0x6e, 0x1f,
	0xaf, 0x61, 0xea, 0x7f, 0x42, 0x6d, 0x78, 0x85, 0xe4, 0x3d, 0x4c, 0xb7, 0x7a, 0x4f, 0x68, 0xe2,
	0xa6, 0xf2, 0xff, 0xe9, 0x09, 0x1f, 0xdd, 0x62, 0xfc, 0xa0, 0x2c, 0xc3, 0x1f, 0xbf, 0x7e, 0xff,
	0xdc, 0x3b, 0x24, 0x24, 0xdd, 0xbc, 0x74, 0x53, 0xad, 0xd3, 0x6f, 0xfe, 0xb4, 0xef, 0x27, 0xe3,
	0x77, 0xc3, 0x24, 0x6d, 0xcb, 0x72, 0xec, 0x26, 0xf3, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x3a, 0x09, 0xc7, 0xfc, 0x02, 0x00, 0x00,
}
